[project]
name = "fastapi-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vinícius de Paula Moraes", email = "viniciusmoraes295651@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi-pagination>=0.15.16",
    "fastapi[standard]>=0.141.1",
    "sqlalchemy[asyncio]>=2.0.52",
]

[project.scripts]
fastapi-project = "fastapi_project:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.setuptools.packages.find]
where = ["src"]
